frontend(profile): Add toast messages when user enters incorrect input
bounswe/bounswe2018group9 pull request #372
Opened 2018-12-18 10:33 UTC by didemongu

2018-12-18 10:47 UTC, kemaltulum approved these changes

2018-12-18 12:53 UTC, okyksl requested changes
@didemongu should we need to create separate functions for each message we're going to make? Why not **parametrize each toast** and **utilize a service** for doing this.

2018-12-18 12:53 UTC, okyksl commented on frontend/src/app/profile/pages/public/public.page.ts
> +  async presentToastFollow() {
@didemongu should we need to create separate functions for each message we're going to make? Why not **parametrize each toast** and **utilize a service** for doing this.

2019-01-06 18:51 UTC, kemaltulum approved these changes

2019-01-12 09:44 UTC, okyksl commented
This is already merged. Checkout #392 for changes I requested.

2019-01-12 09:44 UTC, closed without merging